### ISSUE TITLE
both java 6 and 7  should be supported

### ISSUE THREAD

**Issue by freekh** [adept-dm/adept#13]
Check whether both versions work correctly.

For now only 7 is checked.

**Comment by tomasherman** [comment]
everything should compile now, at least, and tests seem to be passing. Is there any reason to suspect that some 'logic' (dependency resolution etc) would work on jdk7 but not on jdk6?

**Comment by freekh** [comment]
Alright! :) cool

No, no good reasons at least. If compiles and passes basics tests it should work fine.

**Comment by tomasherman** [comment]
We can probably close this, then? :)

**Comment by freekh** [comment]
Yep :)
