### ISSUE TITLE
Mercurial and Bazaar Support

### ISSUE THREAD

**Issue by sirinath** [adept-dm/adept#24]
Hi,

Is it possible to support Hg and Bazaar also. If not Bazaar at least Hg.

Suminda

**Comment by freekh** [comment]
Hey Suminda!
So what you are wondering is whether the adept metadata can be versioned by Hg / Bazaar. It is of course possible, but having one platform is easier to maintain. I was wondering why you feel you need it? Your project can be in Hg/bazaar, even cvs, adept stores its metadata somewhere else than inside your project directory. 

Suminda Dharmasena notifications@github.com wrote:

> Hi,
> 
> Is it possible to support Hg and Bazaar also. If not Bazaar at least
> Hg.
> 
> Suminda
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adept-dm/adept/issues/24

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sirinath** [comment]
What I was thinking was if you have a dependency to a particular hash of a project in a repo than artifacts. Or perhaps dependency to head.

**Comment by freekh** [comment]
Ah, yes :)
It is a cool idea. Do you mind posting it on the mailing list? I see you are a member now ;)

**Comment by sirinath** [comment]
OK

**Comment by sirinath** [comment]
I think these issues get posted to the mailing list?
