### ISSUE TITLE
Remove play-json dependency and replace with json-smart 

### ISSUE THREAD

**Issue by freekh** [adept-dm/adept#37]
Right now now there are 2 different ways of reading json files. Adept-lockfile uses json-smart, because it is only 1 small jar. Adept-core uses play-json because I knew it better. We should probably replace play-json with json-smart because it will be more standardized and it will reduce the jar footprint. Must verify that performance is good though.

**Comment by aknuds1** [comment]
I have opted to [standardize](https://github.com/adept-dm/adept/pull/47) on Jackson streaming API. It's slightly clunky, but quite OK and supposedly it should be very performant (20-30% faster than Jackson object mapping).
