### ISSUE TITLE
Move adept.Adept  to adept-core from adepthub-ext 

### ISSUE THREAD

**Issue by freekh** [adept-dm/adept#44]

**Comment by freekh** [comment]
@aknuds1 want this one as well?

**Comment by aknuds1** [comment]
So what you want is for [adepthub-ext](https://github.com/adepthub/adepthub-ext)/adepthub-ext/src/main/scala/adept/Adept.scala to be moved to [adept](https://github.com/adept-dm/adept)/adept-core/src/main/scala/adept/Adept.scala?

**Comment by freekh** [comment]
Yep, that is really all

On June 21, 2014 8:15:03 PM CEST, Arve Knudsen notifications@github.com wrote:

> So what you want is for
> adepthub-ext/adepthub-ext/src/main/scala/adept/Adept.scala to be moved
> to adept/adept-core/src/main/scala/adept/Adept.scala?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adept-dm/adept/issues/44#issuecomment-46760739

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aknuds1** [comment]
There were some ripple effects from the move, so I had to make a few more changes. See my move-adept branches in [adepthub-ext](https://github.com/aknuds1/adepthub-ext/tree/move-adept) and [adepthub](https://github.com/aknuds1/adept/tree/move-adept). After eventually integrating this change in adept master, shall we update the adept submodule in adepthub-ext so that it's in sync?

**Comment by freekh** [comment]
Yep that is great :) 

On June 21, 2014 9:03:45 PM CEST, Arve Knudsen notifications@github.com wrote:

> There were some ripple effects from the move, so I had to make a few
> more changes. See my move-adept branches in
> [adepthub-ext](https://github.com/aknuds1/adepthub-ext/tree/move-adept)
> and [adepthub](https://github.com/aknuds1/adept/tree/move-adept). After
> eventually integrating this change in adept master, shall we update the
> adept submodule in adepthub-ext so that it's in sync?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/adept-dm/adept/issues/44#issuecomment-46761924

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aknuds1** [comment]
See #49.
