### ISSUE TITLE
Remove modules should be possible to do from CLI

### ISSUE THREAD

**Issue by freekh** [adept-dm/adept#9]

**Comment by tomasherman** [comment]
i will take this one to start with

**Comment by freekh** [comment]
Great :) Tell me if there is anything  I can do :)

**Comment by tomasherman** [comment]
What exactly do you mean by remove modules btw? Remove module when preparing for publish, remove cached module?

**Comment by freekh** [comment]
That is a good question :)
The way add works now is it creates or changes the module json file and adds the file with the changes to the git index. 
I guess remove would remove that module from the file (or the file completely) and update the git index with those changes?

**Comment by tomasherman** [comment]
Sure, makes sense.
